name: front
description: "Imperio Gym - App de gestiÃ³n deportiva"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.10.0
  json_annotation: ^4.9.0
  intl: ^0.19.0
  universal_html: ^2.2.4
  photo_view: ^0.15.0
  cached_network_image: ^3.3.1
  youtube_player_flutter: 9.1.3
  http: ^1.2.2
  audioplayers: ^6.1.0
  image_picker: ^1.1.2
  flutter_inappwebview: ^6.0.0
  circular_countdown_timer: ^0.2.0
  flutter_background_service: ^5.0.7
  wakelock_plus: ^1.2.0
  workmanager: ^0.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/logo.png
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"
